autofetch_sources: True

dependencies:
  - OpenZeppelin/openzeppelin-contracts@5.0.0

compiler:
  solc:
    version: 0.8.28
    evm_version: prague
    optimizer:
      enabled: true
      runs: 200
    remappings:
      - "@openzeppelin=OpenZeppelin/openzeppelin-contracts@5.0.0"
